# Generated by Django 2.0 on 2018-01-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='notes',
            field=models.TextField(null=True, verbose_name='Department Notes'),
        ),
    ]
