# Generated by Django 2.0 on 2018-03-02 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_department_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_by_userid',
            field=models.CharField(default='iadb_sys', max_length=12, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='department',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created`'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(help_text='A name for the department or process area', max_length=50, unique=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='notes',
            field=models.TextField(help_text='(Optional) Brief notes or comments about the department.\n                     Auditor-to-Auditor.', null=True, verbose_name='Department Notes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dept',
            field=models.ForeignKey(help_text='(Optional) The department / work area for a user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='E-mail address for person.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this an active person record?', verbose_name='Active Flag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_first',
            field=models.CharField(help_text="Person's first name.", max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_last',
            field=models.CharField(help_text="Person's last name.", max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.CharField(help_text='(Optional) ACME Co. user name / user id.', max_length=50, null=True),
        ),
    ]
