# Generated by Django 2.0 on 2018-03-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180309_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='notes',
        ),
        migrations.AddField(
            model_name='department',
            name='note',
            field=models.TextField(help_text='(Optional) Brief notes or comments about the department.\n                     Auditor-to-Auditor.', null=True, verbose_name='Note'),
        ),
    ]
