# Generated by Django 2.0 on 2018-01-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=40, verbose_name='First Name')),
                ('name_last', models.CharField(max_length=40, verbose_name='Last Name')),
                ('user_id', models.CharField(max_length=12, verbose_name='User ID')),
                ('email', models.EmailField(max_length=254, unique='True')),
                ('is_active', models.BooleanField(default='True', verbose_name='Is Active')),
                ('date_qualified', models.DateField(verbose_name='Date Qualified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Added to IADB')),
                ('completed_audit_count', models.IntegerField(default=0, verbose_name='Completed Audit Count')),
                ('is_loto_qualified', models.BooleanField(verbose_name='Is LOTO Qualified')),
                ('created_by_userid', models.CharField(default='admin', max_length=12, verbose_name='Created by user')),
            ],
            options={
                'ordering': ['name_last', 'name_first'],
            },
        ),
        migrations.CreateModel(
            name='AuditorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32, unique='True')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Added to IADB')),
                ('created_by_userid', models.CharField(blank='True', default='Admin', max_length=12, verbose_name='Created by user')),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'ordering': ['role_name'],
            },
        ),
        migrations.AddField(
            model_name='auditor',
            name='roles',
            field=models.ManyToManyField(to='auditors.AuditorRole', verbose_name='Role(s)'),
        ),
    ]
