# Generated by Django 2.0 on 2018-01-01 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Record Created')),
                ('created_by_userid', models.CharField(blank='True', max_length=12, verbose_name='Created by user')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auditors.Auditor')),
            ],
            options={
                'ordering': ['-created', 'event'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Event Date-Time')),
                ('event_type', models.CharField(choices=[('MO', 'Monthly Auditor Training/Meeting'), ('CT', 'Candidate Training'), ('QA', 'Quality Ambassador Meeting'), ('RC', 'RCACI Meeting'), ('OE', 'Other Event')], default='MO', max_length=2)),
                ('event_desc', models.CharField(blank='True', max_length=50, verbose_name='Event Description')),
                ('duration_min', models.PositiveIntegerField(blank='True', default=60, verbose_name='Duration (min)')),
                ('allow_checkin', models.BooleanField(default='True', verbose_name='Allow Check-ins')),
                ('checkin_window', models.PositiveIntegerField(default=60, verbose_name='Check-in Window')),
                ('notes', models.TextField(blank='True', max_length=500, verbose_name='Meeting Notes')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Added to IADB')),
                ('created_by_userid', models.CharField(blank='True', default='Admin', max_length=12, verbose_name='Created by user')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['-date_time'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Event'),
        ),
    ]
