# Generated by Django 2.0 on 2018-01-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MO', 'Monthly Auditor Training/Meeting'), ('CT', 'Candidate Training'), ('OE', 'Other Event')], default='MO', max_length=2),
        ),
    ]
