# Generated by Django 2.0 on 2018-01-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique='True', verbose_name='Process Name')),
                ('frequency', models.PositiveSmallIntegerField(default=1, verbose_name='Frequency')),
                ('is_active', models.BooleanField(default='True', verbose_name='Is Active?')),
                ('notes', models.TextField(blank='True', max_length=500, verbose_name='Note(s)')),
                ('iadb1_id', models.PositiveIntegerField(default=None, null='True', verbose_name='IADB1 ID#')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Added to IADB')),
                ('created_by_userid', models.CharField(max_length=12, verbose_name='Created by user')),
            ],
            options={
                'verbose_name_plural': 'Processes',
                'ordering': ['name'],
            },
        ),
    ]
