# Generated by Django 2.0 on 2018-01-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='created_by_userid',
            field=models.CharField(max_length=12, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='process',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created`'),
        ),
    ]
