# Generated by Django 2.0 on 2018-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_auto_20180106_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='iadb1_id',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='IADB1 ID#'),
        ),
        migrations.AlterField(
            model_name='process',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Process Name'),
        ),
        migrations.AlterField(
            model_name='process',
            name='notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='Note(s)'),
        ),
    ]
