# Generated by Django 2.0 on 2018-01-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_auto_20180113_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='notes',
            field=models.TextField(blank=True, help_text='Any notes or commentary for the Process. Generally\n                              auditor-to-auditor, for reference only.', max_length=500, null=True, verbose_name='Note(s)'),
        ),
    ]
