# Generated by Django 2.0 on 2018-01-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_auto_20180114_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(help_text='Descriptive name for the process area.', max_length=55, unique=True, verbose_name='Process Name'),
        ),
    ]
