# Generated by Django 2.0 on 2018-01-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_auto_20180122_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='A Comment communicates something auditor-to-auditor about the Process,\n                                            such as a lesson learned, suggestion, or other such information. There\n                                            can be multiple comments for a Process.', verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created`')),
                ('created_by_userid', models.CharField(max_length=12, verbose_name='Created By')),
            ],
        ),
        migrations.RemoveField(
            model_name='process',
            name='notes',
        ),
        migrations.AddField(
            model_name='process',
            name='note',
            field=models.TextField(blank=True, help_text='Top-Level  for the Process. Generally\n                                         auditor-to-auditor, for reference only.', max_length=500, null=True, verbose_name='Note(s)'),
        ),
        migrations.AlterField(
            model_name='process',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many times per year the Process\n                                                  should be audited. ( 1 for yearly, 4 for\n                                                  quarterly ).', verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(help_text='Descriptive name for the process area.', max_length=50, unique=True, verbose_name='Process Name'),
        ),
        migrations.AddField(
            model_name='processcomment',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Comments', to='processes.Process'),
        ),
    ]
