# Generated by Django 2.0 on 2018-02-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_auto_20180123_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processcomment',
            options={'ordering': ['process', '-date_created'], 'verbose_name': 'Process Comment', 'verbose_name_plural': 'Process Comments'},
        ),
        migrations.AlterField(
            model_name='processcomment',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='processes.Process', verbose_name='For Process'),
        ),
    ]
