# Generated by Django 2.0 on 2018-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_auto_20180220_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='created_by_userid',
            field=models.CharField(default='iadb_sys', max_length=12, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='process',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many times per year the Process should be audited. ( 1 for\n                     yearly, 4 for quarterly ).', verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='process',
            name='iadb1_id',
            field=models.PositiveIntegerField(default=None, help_text='UID of Process in iadb1. Used for data migration.', null=True, verbose_name='IADB1 ID#'),
        ),
        migrations.AlterField(
            model_name='process',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this Process current in-use. Inactive Processes will NOT be\n                     included in audit processing.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='process',
            name='note',
            field=models.TextField(blank=True, help_text='Top-Level for the Process. Generally auditor-to-auditor, for\n                     reference only.', max_length=500, null=True, verbose_name='Note(s)'),
        ),
        migrations.AlterField(
            model_name='processcomment',
            name='comment',
            field=models.TextField(help_text='A Comment communicates something auditor-to-auditor about the Process,\n                     such as a lesson learned, suggestion, or other such information. There\n                     can be multiple comments for a Process.', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='processcomment',
            name='created_by_userid',
            field=models.CharField(default='iadb_sys', max_length=12, verbose_name='Created By'),
        ),
    ]
