# Generated by Django 2.0 on 2018-01-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, verbose_name='Identifier')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('note', models.TextField(blank='True', max_length=500, null='True', verbose_name='Note(s)')),
                ('coverage_by', models.CharField(choices=[('S', 'Self'), ('P', 'Parent'), ('C', 'Child(ren)'), ('NA', 'N/A')], default='S', max_length=2)),
                ('is_active', models.BooleanField(default='True', verbose_name='Active Flag')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Added to IADB')),
                ('created_by_userid', models.CharField(max_length=12, verbose_name='Created by user')),
                ('parent', models.ForeignKey(blank='True', null='True', on_delete='Protect', to='requirements.Requirement', verbose_name='Parent')),
            ],
            options={
                'ordering': ['identifier', 'standard'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Standard Name')),
                ('revision', models.CharField(max_length=5, verbose_name='Revision')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
                ('description', models.CharField(max_length=80, verbose_name='Description')),
                ('date_active', models.DateField(verbose_name='Date Active')),
                ('date_inactive', models.DateField(blank='True', null='True', verbose_name='Date Retired:')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added to IADB')),
                ('created_by_userid', models.CharField(default='Admin', max_length=12, verbose_name='Created by user')),
            ],
            options={
                'ordering': ['name', '-revision'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together={('name', 'revision')},
        ),
        migrations.AddField(
            model_name='requirement',
            name='standard',
            field=models.ForeignKey(on_delete='Protect', to='requirements.Standard', verbose_name='From Standard'),
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('standard', 'identifier')},
        ),
    ]
