# Generated by Django 2.0 on 2018-01-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='description',
            field=models.CharField(max_length=120, verbose_name='Description'),
        ),
    ]
