# Generated by Django 2.0 on 2018-01-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_auto_20180101_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank='True', null='True', on_delete='Protect', related_name='children', to='requirements.Requirement', verbose_name='Parent'),
        ),
    ]
