# Generated by Django 2.0 on 2018-01-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_auto_20180103_2016'),
        ('requirements', '0003_auto_20180104_0639'),
    ]

    operations = [
    ]
