# Generated by Django 2.0 on 2018-01-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_merge_20180105_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['identifier', 'standard'], 'verbose_name': 'Requirement', 'verbose_name_plural': 'Requirements'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['name', '-revision'], 'verbose_name': 'Standard', 'verbose_name_plural': 'Standards'},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='coverage_by',
            field=models.CharField(choices=[('S', 'Self'), ('P', 'Parent'), ('C', 'Child(ren)'), ('NA', 'N/A')], default='S', help_text="Covered by. Choices are:\n                                                SELF = This requirement is a\n                                                coverage point.  PARENT = This\n                                                requirment inherits the parent's coverage,\n                                                typically used for standard clauses which\n                                                end up being long lists and thus don't\n                                                warrant individual questions.  CHILD(REN) = \n                                                this requirement delegates\n                                                coverage to child(ren) requirements. \n                                                Typically used for 'placeholder' requriements,\n                                                such as section headers.", max_length=2, verbose_name='Coverage By'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.CharField(help_text='Brief Description of Requirement.\n                                                Often the section of the Standard it derives\n                                                from.', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='identifier',
            field=models.CharField(help_text='Requirement identifier.', max_length=20, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_active',
            field=models.BooleanField(default='True', help_text='Is requirement active? Only active\n                                                 requirements will be considered in \n                                                 coverage logic.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='note',
            field=models.TextField(blank='True', help_text='Auditor-to-Audit note(s) that convey additional\n                                         information that may be useful.\n\n                                         Often explains delegation of coverage.', max_length=500, null='True', verbose_name='Note(s)'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank='True', help_text='The Parent requirement (if any) of this\n                                            requirement. Used in conjunction with \n                                            COVERAGE (above) to determine coverage\n                                             obligations.', null='True', on_delete='Protect', related_name='children', to='requirements.Requirement', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='standard',
            field=models.ForeignKey(help_text='The identifier\n                                 or name of the Standard this Requirement traces to.', on_delete='Protect', to='requirements.Standard', verbose_name='From Standard'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='date_active',
            field=models.DateField(help_text='Date the Standard was adopted for audit purposes.', verbose_name='Date Active'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='date_inactive',
            field=models.DateField(blank='True', help_text='Date the Standard was retired from audit  \n                            purposes.', null='True', verbose_name='Date Retired'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='description',
            field=models.CharField(help_text='The description or title of the Standard. ', max_length=120, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='is_active',
            field=models.BooleanField(help_text='Is this Standard currently in-use for audit purposes?\n                                         Inactive Standards will not be included in audit\n                                         processing.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.CharField(help_text='The name of the Standard, the primary identifier.', max_length=20, verbose_name='Standard Name'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='revision',
            field=models.CharField(help_text='Identifier for the exact version of the  \n                                Standards being used.', max_length=5, verbose_name='Revision'),
        ),
    ]
