# Generated by Django 2.0 on 2018-01-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_auto_20180113_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='coverage_by',
            field=models.CharField(choices=[('S', 'Self'), ('P', 'Parent'), ('C', 'Child(ren)'), ('NA', 'N/A')], default='S', help_text="Covered by. Choices are:\n                                                SELF = This Requirement is a\n                                                coverage point.  PARENT = This\n                                                requirment inherits the parent's coverage,\n                                                typically used for standard clauses which\n                                                end up being long lists and thus don't\n                                                warrant individual questions.  CHILD(REN) =\n                                                this Requirement delegates\n                                                coverage to child(ren) Requirements.\n                                                Typically used for 'placeholder' requriements,\n                                                such as section headers.", max_length=2, verbose_name='Coverage By'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_active',
            field=models.BooleanField(default='True', help_text='Is Requirement active? Only active\n                                                 Requirements will be considered in\n                                                 coverage logic.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank='True', help_text='The Parent Requirement (if any) of this\n                                            Requirement. Used in conjunction with\n                                            COVERAGE (above) to determine coverage\n                                             obligations.', null='True', on_delete='Protect', related_name='children', to='requirements.Requirement', verbose_name='Parent'),
        ),
    ]
