# Generated by Django 2.0 on 2018-01-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0007_auto_20180118_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_identifier',
            field=models.CharField(help_text="ACME Co.'s internal\n                                       identification number for the Document.", max_length=20, unique=True, verbose_name='Doc ID'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='standard',
            field=models.ForeignKey(help_text='The identifier or name of the Standard this\n                                              Requirement traces to.', on_delete='Protect', to='requirements.Standard', verbose_name='From Standard'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['identifier', 'standard'], name='requirement_identif_358294_idx'),
        ),
    ]
