# Generated by Django 2.0 on 2018-03-02 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_auto_20180120_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='date_added',
        ),
        migrations.AddField(
            model_name='standard',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created`'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by_userid',
            field=models.CharField(default='iadb_sys', max_length=12, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created`'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_identifier',
            field=models.CharField(help_text="ACME Co.'s internal identification number for the Document.", max_length=20, unique=True, verbose_name='Doc ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='note',
            field=models.TextField(blank=True, help_text='(Optional) Auditor-to-Auditor internal note(s) that convey additional\n                     information which may be useful or good to know.', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='coverage_by',
            field=models.CharField(choices=[('S', 'Self'), ('P', 'Parent'), ('C', 'Child(ren)'), ('NA', 'N/A')], default='S', help_text="Covered by. Choices are: SELF = This requirement is a coverage point.\n                     PARENT = This requirment inherits the parent's coverage, typically used\n                     for standard clauses which end up being long lists and thus don't\n                     warrant individual questions.  CHILD(REN) = this requirement delegates\n                     coverage to child(ren) requirements. Typically used for 'placeholder'\n                     requriements, such as section headers.", max_length=2, verbose_name='Coverage By'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_by_userid',
            field=models.CharField(default='iadb_sys', max_length=12, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created`'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.CharField(help_text='Brief Description of Requirement. Often the section of the Standard\n                     it derives from.', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_active',
            field=models.BooleanField(default='True', help_text='Is requirement active? Only active Requirements will be considered in\n                     coverage logic.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='note',
            field=models.TextField(blank=True, help_text='Auditor-to-Auditor note(s) that convey additional information that\n                     may be useful.\nOften explains delegation of coverage.', max_length=500, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank='True', help_text='The Parent requirement (if any) of this requirement. Used in\n                     conjunction with COVERAGE (above) to determine coverage obligations.', null='True', on_delete='Protect', related_name='children', to='requirements.Requirement', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='standard',
            field=models.ForeignKey(help_text='The identifier or name of the Standard this Requirement traces to.', on_delete='Protect', to='requirements.Standard', verbose_name='From Standard'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='created_by_userid',
            field=models.CharField(default='iadb_sys', max_length=12, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='date_inactive',
            field=models.DateField(blank='True', help_text='Date the Standard was retired from audit purposes.', null='True', verbose_name='Date Retired'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='is_active',
            field=models.BooleanField(help_text='Is this Standard currently in-use for audit purposes? Inactive\n                     Standards will not be included in audit processing.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='revision',
            field=models.CharField(help_text='Identifier for the exact version of the Standards being used.', max_length=5, verbose_name='Revision'),
        ),
    ]
