# Generated by Django 2.0 on 2018-01-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(blank='False', null='False')),
                ('type', models.CharField(choices=[('Q', 'Quarter')], default='Q', max_length=1)),
                ('period', models.SmallIntegerField(blank='False', null='False')),
                ('date_start', models.DateField(blank='False', verbose_name='Period Start Date')),
                ('date_end', models.DateField(blank='False', verbose_name='Period Start Date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Added to IADB')),
                ('created_by_userid', models.CharField(max_length=12, verbose_name='Created by user')),
            ],
        ),
    ]
