# Generated by Django 2.0 on 2018-01-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditperiod',
            name='period',
            field=models.SmallIntegerField(blank='False', default='1', null='False'),
        ),
        migrations.AlterField(
            model_name='auditperiod',
            name='year',
            field=models.SmallIntegerField(blank='False', default='2018', null='False'),
        ),
    ]
