# Generated by Django 2.0 on 2018-01-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auto_20180101_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditperiod',
            options={'ordering': ['-year', 'period']},
        ),
        migrations.AlterUniqueTogether(
            name='auditperiod',
            unique_together={('year', 'period')},
        ),
    ]
