# Generated by Django 2.0 on 2018-01-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20180101_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditperiod',
            name='date_end',
            field=models.DateField(blank='False', verbose_name='Period End Date'),
        ),
    ]
