# Generated by Django 2.0 on 2018-01-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_auto_20180103_2016'),
        ('audits', '0004_auto_20180103_0709'),
    ]

    operations = [
    ]
