# Generated by Django 2.0 on 2018-01-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_auto_20180113_1501'),
        ('requirements', '0005_auto_20180113_1501'),
        ('audits', '0005_merge_20180105_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditMasterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Auditor-to-Auditor internal notes, for reference\n                                         only.', null=True, verbose_name='Note')),
                ('for_process', models.ForeignKey(help_text='The Process this Audit is defined for.', on_delete='Protect', related_name='audit_master_template', to='processes.Process', verbose_name='Process Audited')),
                ('requirements', models.ManyToManyField(help_text='Requirements that this audit should \n                                                       cover.', related_name='audit_master_template', to='requirements.Requirement', verbose_name='Requirement')),
            ],
        ),
        migrations.AlterModelOptions(
            name='auditperiod',
            options={'ordering': ['-year', 'period'], 'verbose_name': 'Audit Period', 'verbose_name_plural': 'Audit Periods'},
        ),
    ]
