# Generated by Django 2.0 on 2018-01-13 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_auto_20180113_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditmastertemplate',
            options={'ordering': ['for_process'], 'verbose_name': 'Audit Master Template', 'verbose_name_plural': 'Audit Master Templates'},
        ),
        migrations.AddField(
            model_name='auditmastertemplate',
            name='created_by_userid',
            field=models.CharField(default='Admin', max_length=12, verbose_name='Created by user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditmastertemplate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Added to IADB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditmastertemplate',
            name='is_active',
            field=models.BooleanField(default='True', help_text='Is Audit Master Template active? Only active\n                                                 Master Templates will be available for \n                                                 creating Audits', verbose_name='Active'),
        ),
    ]
