# Generated by Django 2.0 on 2018-01-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_auto_20180113_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditmastertemplate',
            name='note',
            field=models.TextField(blank=True, help_text='Auditor-to-Auditor internal notes. For reference\n                                         only.', null=True, verbose_name='Note'),
        ),
    ]
