# Generated by Django 2.0 on 2018-01-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_auto_20180120_1407'),
        ('processes', '0005_auto_20180114_1518'),
        ('audits', '0008_auto_20180114_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Auditor-to-Auditor internal notes. For reference\n                                         only.', null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default='True', help_text='Is Audit Master Template active? Only active\n                                                 Master Templates will be available for\n                                                 creating Audits', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Added to IADB')),
                ('created_by_userid', models.CharField(max_length=12, verbose_name='Created by user')),
                ('documents', models.ManyToManyField(help_text='Documents relevant to the Process this audit\n                                                    covers.', related_name='audit_templates', to='requirements.Document', verbose_name='Document(s)')),
                ('for_process', models.ForeignKey(help_text='The Process this Audit is defined for.', on_delete='Protect', related_name='audit_master_template', to='processes.Process', verbose_name='Process Audited')),
                ('requirements', models.ManyToManyField(help_text='Requirements that this audit should\n                                                       cover.', related_name='audit_master_template', to='requirements.Requirement', verbose_name='Requirement(s)')),
            ],
            options={
                'verbose_name': 'Audit Template',
                'verbose_name_plural': 'Audit Templates',
                'ordering': ['for_process'],
            },
        ),
        migrations.RemoveField(
            model_name='auditmastertemplate',
            name='for_process',
        ),
        migrations.RemoveField(
            model_name='auditmastertemplate',
            name='requirements',
        ),
        migrations.DeleteModel(
            name='AuditMasterTemplate',
        ),
    ]
