# Generated by Django 2.0 on 2018-01-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_auto_20180120_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditperiod',
            name='created_by_userid',
            field=models.CharField(max_length=20, verbose_name='Created by user'),
        ),
        migrations.AlterField(
            model_name='auditperiod',
            name='date_end',
            field=models.DateField(blank='False', help_text='Date the period ends.', verbose_name='Period End Date'),
        ),
        migrations.AlterField(
            model_name='auditperiod',
            name='date_start',
            field=models.DateField(blank='False', help_text='Date the period begins.', verbose_name='Period Start Date'),
        ),
        migrations.AlterField(
            model_name='auditperiod',
            name='period',
            field=models.SmallIntegerField(blank='False', default='1', help_text='Unique ID of the period within the Year', null='False', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='auditperiod',
            name='type',
            field=models.CharField(choices=[('Q', 'Quarter')], default='Q', help_text='Currently the only available type is Quarter, but\n                                         could be expanded in future if required.', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='auditperiod',
            name='year',
            field=models.SmallIntegerField(blank='False', default='2018', help_text='Audit Period Year', null='False', verbose_name='Year'),
        ),
    ]
