# Generated by Django 2.0 on 2018-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_auto_20180220_0815'),
        ('audits', '0011_auto_20180122_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('IP', 'In-Progress'), ('C', 'Completed'), ('DS', 'Delinquent: Not Started'), ('DF', 'Delinquent: Not Completed')], default='S', help_text='Audit Status. An audit can be in one of the following\n                                           states: Scheduled, In-Progress, Completed, Delinquent Start,\n                                           or Delinquent Finish.', max_length=2, verbose_name='Status')),
                ('for_process', models.ForeignKey(help_text='The Process this Audit is defined for.', on_delete='Protect', related_name='audit_header', to='processes.Process', verbose_name='Process To Audit')),
                ('period_scheduled', models.ForeignKey(help_text='The period this particular audit is scheduled\n                                         for.', on_delete='Protect', related_name='period_scheduled', to='audits.AuditPeriod', verbose_name='Period Scheduled')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['-period_scheduled__year', '-period_scheduled__period', 'for_process__process_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='auditheader',
            unique_together={('for_process', 'period_scheduled')},
        ),
    ]
