# Generated by Django 2.0 on 2018-01-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(blank='False', max_length=512, verbose_name='Question Text')),
                ('q_notes', models.TextField(blank='True', verbose_name='Question Notes')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Added to IADB')),
                ('created_by_userid', models.CharField(blank='True', default='Admin', max_length=12, verbose_name='Created by user')),
                ('q_status', models.CharField(choices=[('AC', 'Active'), ('IS', 'Inactive: Save'), ('IP', 'Inactive: Purge')], default='AC', max_length=2)),
                ('q_version', models.PositiveIntegerField(default=1, null='FALSE', verbose_name='Version')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
